hash-format = "sha256"

[[files]]
file = ".githooks/pre-commit"

[[files]]
file = ".nojekyll"

[[files]]
file = ".published-files"

[[files]]
file = "config/alexsmobs.toml"

[[files]]
file = "config/canary.properties"

[[files]]
file = "config/sporeconfig.toml"

[[files]]
file = "config/sporedata.toml"

[[files]]
file = "kubejs/data/biomagic/forge/biome_modifier/visceral_heap_biomancy_flesh.json"

[[files]]
file = "kubejs/data/biomagic/forge/biome_modifier/visceral_heap_flesh_livestock.json"

[[files]]
file = "kubejs/data/biomagic/functions/netherportal.mcfunction"

[[files]]
file = "kubejs/data/biomagic/functions/recipe_biomancy.mcfunction"

[[files]]
file = "kubejs/data/biomagic/functions/recipe_botania.mcfunction"

[[files]]
file = "kubejs/data/biomagic/functions/recipe_create.mcfunction"

[[files]]
file = "kubejs/data/biomagic/functions/recipe_evilcraft.mcfunction"

[[files]]
file = "kubejs/data/biomagic/functions/recipe_halogen.mcfunction"

[[files]]
file = "kubejs/data/biomagic/functions/recipe_hex.mcfunction"

[[files]]
file = "kubejs/data/biomagic/functions/recipe_malum.mcfunction"

[[files]]
file = "kubejs/data/biomagic/functions/recipe_occultism.mcfunction"

[[files]]
file = "kubejs/data/biomagic/functions/testpad.mcfunction"

[[files]]
file = "kubejs/data/biomagic/functions/testpad_clear.mcfunction"

[[files]]
file = "kubejs/data/biomagic/tags/blocks/infectable_masonry.json"

[[files]]
file = "kubejs/data/biomagic/tags/blocks/infectable_soil.json"

[[files]]
file = "kubejs/data/biomagic/tags/blocks/infectable_timber.json"

[[files]]
file = "kubejs/data/biomagic/tags/blocks/infection_immune.json"

[[files]]
file = "kubejs/data/biomagic/worldgen/configured_feature/buried_cradle.json"

[[files]]
file = "kubejs/data/biomagic/worldgen/configured_feature/malignant_flesh_blob.json"

[[files]]
file = "kubejs/data/biomagic/worldgen/configured_feature/malignant_flesh_veins.json"

[[files]]
file = "kubejs/data/biomagic/worldgen/placed_feature/buried_cradle.json"

[[files]]
file = "kubejs/data/biomagic/worldgen/placed_feature/malignant_flesh_blob.json"

[[files]]
file = "kubejs/data/biomagic/worldgen/placed_feature/malignant_flesh_veins.json"

[[files]]
file = "kubejs/data/biomancy/tags/blocks/allow_veins_to_attach.json"

[[files]]
file = "kubejs/data/biomancy/tags/blocks/decay_destructible.json"

[[files]]
file = "kubejs/data/biomesoplenty/worldgen/configured_feature/blood_lake.json"

[[files]]
file = "kubejs/data/biomesoplenty/worldgen/configured_feature/blood_spring.json"

[[files]]
file = "kubejs/data/minecraft/tags/blocks/animals_spawnable_on.json"

[[files]]
file = "kubejs/data/minecraft/tags/blocks/mineable/axe.json"

[[files]]
file = "kubejs/data/minecraft/tags/blocks/mineable/hoe.json"

[[files]]
file = "kubejs/data/sons_of_sins/tags/items/is_slicer.json"

[[files]]
file = "kubejs/data/spore/spore_block_conversion/default_conversions.json"

[[files]]
file = "kubejs/data/spore/worldgen/structure_set/biomass_tower.json"

[[files]]
file = "kubejs/data/spore/worldgen/structure_set/cathedral.json"

[[files]]
file = "kubejs/data/spore/worldgen/structure_set/cell.json"

[[files]]
file = "kubejs/data/spore/worldgen/structure_set/celltower.json"

[[files]]
file = "kubejs/data/spore/worldgen/structure_set/church.json"

[[files]]
file = "kubejs/data/spore/worldgen/structure_set/hospital.json"

[[files]]
file = "kubejs/data/spore/worldgen/structure_set/lab.json"

[[files]]
file = "kubejs/data/spore/worldgen/structure_set/lodge.json"

[[files]]
file = "kubejs/data/spore/worldgen/structure_set/mass_grave.json"

[[files]]
file = "kubejs/data/spore/worldgen/structure_set/military_camp.json"

[[files]]
file = "kubejs/data/spore/worldgen/structure_set/prison.json"

[[files]]
file = "kubejs/server_scripts/biomagic_capstone.js"

[[files]]
file = "kubejs/server_scripts/biomagic_fixes.js"

[[files]]
file = "kubejs/server_scripts/biomagic_invariants.js"

[[files]]
file = "kubejs/server_scripts/biomagic_loot.js"

[[files]]
file = "kubejs/server_scripts/biomagic_mosquito.js"

[[files]]
file = "kubejs/server_scripts/biomagic_visceral_heap.js"

[[files]]
file = "mods/alexs-mobs.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
metafile = true

[[files]]
file = "mods/biofactory.pw.toml"
metafile = true

[[files]]
file = "mods/biomancy.pw.toml"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
metafile = true

[[files]]
file = "mods/c2mef.pw.toml"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/cyclops-core.pw.toml"
metafile = true

[[files]]
file = "mods/death-muffler-fix.pw.toml"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
metafile = true

[[files]]
file = "mods/evilcraft.pw.toml"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/fps-reducer.pw.toml"
metafile = true

[[files]]
file = "mods/fungal-infectionspore.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
metafile = true

[[files]]
file = "mods/hex-casting.pw.toml"
metafile = true

[[files]]
file = "mods/inline.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jei-malum.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/justenoughbreeding.pw.toml"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
metafile = true

[[files]]
file = "mods/lodestone.pw.toml"
metafile = true

[[files]]
file = "mods/lootjs.pw.toml"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/lost-cities-modern-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/lostcitiesfilter.pw.toml"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
metafile = true

[[files]]
file = "mods/malum.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/mob-grinding-utils.pw.toml"
metafile = true

[[files]]
file = "mods/mob-player-animator.pw.toml"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modonomicon.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/occultism-kubejs.pw.toml"
metafile = true

[[files]]
file = "mods/occultism.pw.toml"
metafile = true

[[files]]
file = "mods/ore-vein-miner.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/smartbrainlib.pw.toml"
metafile = true

[[files]]
file = "mods/sons-of-sins.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-inventory-interactions.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-item-actions.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-jei-index.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/the-lost-cities.pw.toml"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
metafile = true

[[files]]
file = "packstamp.txt"

[[files]]
file = "prism-prelaunch.sh"
