name = "Bio Magic"
author = "voidfemme"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dad188aa6d43f6a2603803df8ff5a261946eb5a18facab8688a82b5bf77e0036"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
