name = "Bio Magic"
author = "voidfemme"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acdf73f133e37a0bf7f56199259745a741599a09977ada0fad50e62792984e6a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
