name = "Bio Magic"
author = "voidfemme"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1724489f74f6ba73b773d3e1f678ee68f8704eb05a09f4382a92b3c8580c129f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
